# Numpy 

In [1]:
import numpy as np

## numpy array

In [15]:
mylist= [20,30,40]

In [16]:
type(mylist)

list

In [21]:
np.array(mylist)

array([20, 30, 40])

In [22]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]

In [23]:
type(matrixList)

list

In [24]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# Numpy methods

## arange

In [27]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [35]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [36]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [38]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

## eye

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [44]:
np.random.randn(5)

array([ 0.20577456,  0.85762515,  0.30550236, -0.11403077,  1.001651  ])

In [45]:
np.random.randn(3,3)

array([[ 2.47387915, -1.05501506,  1.68594726],
       [-0.53714104, -1.44498359, -1.6976751 ],
       [-1.71882673, -0.03609342, -0.80286475]])

In [46]:
np.random.randint(1,10)

8

In [47]:
np.random.randint(1,10,5)

array([3, 7, 6, 6, 3])

In [50]:
myNumpyArray = np.arange(10)

In [51]:
myNumpyArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
myRandomArray = np.random.randint(0,50,5)

In [59]:
myRandomArray

array([ 9,  6, 47,  7, 12])

# numpy array methods

In [61]:
myNumpyArray.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
myNumpyArray.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
myNumpyArray.max()

9

In [64]:
myNumpyArray.min()

0

In [65]:
myNumpyArray.argmax()

9

In [66]:
myNumpyArray.argmin()

0

In [73]:
reshapeArray = myNumpyArray.reshape(2,5)

In [74]:
reshapeArray.shape

(2, 5)

## python slicing

In [82]:
myNumpyArray[3:5] = -5

In [84]:
myNumpyArray

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9])

In [85]:
newArray = np.arange(0,24)

In [87]:
newArray[6:11]

array([ 6,  7,  8,  9, 10])

In [88]:
slicingArray = newArray[:10]

In [90]:
slicingArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
slicingArray[:]=500

In [92]:
slicingArray

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500])

In [93]:
newArray

array([500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## Numpy slicing

In [95]:
exampleArray = np.arange(0,24)

In [96]:
copyofexampleArray = exampleArray.copy()

In [97]:
copyofexampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [98]:
copyofexampleArraySlicing =copyofexampleArray[3:6]

In [99]:
copyofexampleArraySlicing[:] = 800

In [100]:
copyofexampleArraySlicing

array([800, 800, 800])

In [101]:
copyofexampleArray

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [102]:
exampleArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [121]:
matrixArray = np.random.randn(3,3)

In [122]:
matrixArray

array([[ 1.03622997,  1.19356922, -1.06100025],
       [-1.20747795, -0.63417593,  0.84425565],
       [ 1.73845366, -0.36318275, -0.59270611]])

In [123]:
matrixArray[0]

array([ 1.03622997,  1.19356922, -1.06100025])

In [124]:
matrixArray[0][1]

1.193569217107194

In [125]:
matrixArray[0,1]

1.193569217107194

In [126]:
matrixArray[1:,2]

array([ 0.84425565, -0.59270611])

In [127]:
matrixArray[1:,1]

array([-0.63417593, -0.36318275])

In [149]:
newMatrix= np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24],])

In [150]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [151]:
newMatrix[2]

array([10, 11, 12, 13, 14])

In [154]:
newMatrix[[0,4,2]]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14]])

## operations

In [159]:
operationArray = np.random.randint(1,100,20)

In [160]:
operationArray

array([11, 84, 74, 25, 41, 83, 79, 66,  2,  7, 85, 30, 76, 78, 72, 16, 85,
       69, 39, 94])

In [161]:
operationArray > 24

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [164]:
resultArray = operationArray > 24

In [165]:
resultArray

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [166]:
operationArray[resultArray]

array([84, 74, 25, 41, 83, 79, 66, 85, 30, 76, 78, 72, 85, 69, 39, 94])

In [167]:
resultArray [:] = True

In [169]:
operationArray[resultArray]

array([11, 84, 74, 25, 41, 83, 79, 66,  2,  7, 85, 30, 76, 78, 72, 16, 85,
       69, 39, 94])

In [170]:
operationArray[operationArray>50]

array([84, 74, 83, 79, 66, 85, 76, 78, 72, 85, 69, 94])

In [171]:
lastArray = np.arange(0,24)

In [172]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [173]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [174]:
lastArray*lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [175]:
lastArray-lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [176]:
lastArray/lastArray

C:\Users\furka\AppData\Local\Temp\ipykernel_10592\3067326312.py:1: RuntimeWarning: invalid value encountered in divide
  lastArray/lastArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [178]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [179]:
np.max(lastArray)

23

In [180]:
np.min(lastArray)

0