In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#veri kümesi
data = pd.read_csv('Wine.csv')
x = data.iloc[:,0:13]
y = data.iloc[:,13].values

# eğitim ve test kümelerinin bölünmesi
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)

#ölçekleme
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [3]:
# PCA
from sklearn.decomposition import PCA
pca = PCA(n_components= 2)

x_train2 = pca.fit_transform(x_train)
x_test2 = pca.transform(x_test) #veri boyutlandırması

# PCA dönüşümünden gelen LR
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit( x_train,y_train)

#pca dönüşümünden sonra gelen LR
classifier2 = LogisticRegression(random_state=0)
classifier2.fit( x_train2,y_train)

#tahminler
y_pred = classifier.predict( x_test)

y_pred2 = classifier2.predict( x_test2)

from sklearn.metrics import confusion_matrix
# actual / PCA olmadan çıkan sonuç
cm = confusion_matrix(y_test,y_pred)
print(' gerçek / PCA siz')
print(cm)
# actual / PCA sonrası çıkan sonuç
cm2 = confusion_matrix(y_test,y_pred2)
print('gercek / PCA ile')
print(cm2)

# PCA sonrası / PCA öncesi
cm3 = confusion_matrix(y_test,y_pred2)
print('PCA siz ve PCA ile')
print(cm3)

 gerçek / PCA siz
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
gercek / PCA ile
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
PCA siz ve PCA ile
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]


In [6]:
# LDA
from sklearn.discriminant_analysis import  LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)

x_train_lda =lda.fit_transform(x_train,y_train) # pca den fark y_train de veriyoruz. (sınıfların olduğu boyutu almalı)
x_test_lda = lda.transform(x_test)

# LDA dönüşümünden sonra
classifier_lda = LogisticRegression(random_state=0)
classifier_lda.fit( x_train_lda,y_train)

# LDA verisini tahmin et
y_pred_lda = classifier_lda.predict( x_test_lda)

# LDA sonrası / orijinal
print('lda ve orijinal')
cm4 = confusion_matrix(y_pred,y_pred_lda)
print(cm4)

lda ve orijinal
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


array([1, 3, 2, 1, 2, 2, 1, 3, 2, 2, 3, 3, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1], dtype=int64)